openapi: 3.0.0
info:
  version: 1.0.0
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
paths:
  /hello:
    get:
      description: Returns a hello
      responses:
        '200':
          description: Say Hello
