openapi: 3.0.0
info:
  description: A sample API to illustrate OpenAPI concepts
  title: Sample API
  version: 1.0.0
servers:
- url: /
paths:
  /hello:
    get:
      description: Returns a hello
      responses:
        "200":
          description: Say Hello
      x-accepts: application/json
components:
  schemas: {}
